//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boat : Product
    {
        public string FullName { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> TypeId { get; set; }
        public bool Featured { get; set; }
        public string Manu { get; set; }
        public string ManuTxt { get; set; }
        public string ManuAdvert { get; set; }
        public string ManuLink { get; set; }
        public string CurrentBuilder { get; set; }
        public string DesignHistory { get; set; }
    }
}
