//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothSize
    {
        public int Id { get; set; }
        public int ClothId { get; set; }
        public string Size { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
