//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth : Product
    {
        public Cloth()
        {
            this.ClothSizes = new HashSet<ClothSize>();
        }
    
        public string Colour { get; set; }
        public string Style { get; set; }
        public Nullable<int> MerchantCategoryId { get; set; }
        public int BrandId { get; set; }
    
        public virtual ICollection<ClothSize> ClothSizes { get; set; }
        public virtual MerchantCategory MerchantCategory { get; set; }
        public virtual Brand Brand { get; set; }
    }
}
