//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth : Product
    {
        public Cloth()
        {
            this.Styles = new HashSet<Style>();
            this.Departments = new HashSet<Department>();
            this.Sizes = new HashSet<Size>();
        }
    
        public Nullable<int> MerchantCategoryId { get; set; }
        public int BrandId { get; set; }
        public Nullable<int> ColourId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public decimal CustomerRating { get; set; }
        public string MerchantCategoryName { get; set; }
    
        public virtual MerchantCategory MerchantCategory { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Style> Styles { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Colour Colour { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Size> Sizes { get; set; }
    }
}
