//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public string Status { get; set; }
        public int PortalId { get; set; }
        public string Category { get; set; }
        public int VendorId { get; set; }
        public string AdvancedCategoryRoot { get; set; }
        public string CountryFilter { get; set; }
        public string CityFilter { get; set; }
        public Nullable<int> StepImport { get; set; }
        public Nullable<int> StepAddToCategories { get; set; }
        public Nullable<int> StepAddImages { get; set; }
    }
}
