//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hierarchy
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public Nullable<int> Depth { get; set; }
        public string Lineage { get; set; }
    }
}
