//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelLocation
    {
        public int Id { get; set; }
        public int HotelId { get; set; }
        public int LocationId { get; set; }
        public int HotelTypeId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual HotelType HotelType { get; set; }
        public virtual Location Location { get; set; }
    }
}
