//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel : Product
    {
        public Nullable<int> Rooms { get; set; }
        public Nullable<decimal> Star { get; set; }
        public Nullable<decimal> CustomerRating { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public int HotelTypeId { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public Nullable<int> GeoNameId { get; set; }
    
        public virtual HotelType HotelType { get; set; }
        public virtual GeoName GeoName { get; set; }
    }
}
