//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantCategory
    {
        public MerchantCategory()
        {
            this.Clothes = new HashSet<Cloth>();
            this.SubMerchantCategories = new HashSet<MerchantCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Cloth> Clothes { get; set; }
        public virtual ICollection<MerchantCategory> SubMerchantCategories { get; set; }
        public virtual MerchantCategory ParentMerchantCategory { get; set; }
    }
}
