//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductSpecs = new HashSet<ProductSpec>();
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public int CreatedByUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Image { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string ExtraDescription { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<int> FeedId { get; set; }
    
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<ProductSpec> ProductSpecs { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Feed Feed { get; set; }
    }
}
