//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectedHotelsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlRule
    {
        public int UrlRuleId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int UserId { get; set; }
        public int RuleType { get; set; }
        public string CultureCode { get; set; }
        public int PortalId { get; set; }
        public Nullable<int> TabId { get; set; }
        public string Parameters { get; set; }
        public Nullable<bool> RemoveTab { get; set; }
        public int RuleAction { get; set; }
        public string Url { get; set; }
        public string RedirectDestination { get; set; }
        public Nullable<int> RedirectStatus { get; set; }
    }
}
